name: Validate Conventional Commits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Commits
        uses: afcody/action-commitlint@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}