name: Nightly Build and Push to Docker Hub

on:
  schedule:
    - cron: "0 8 * * *"  # SF time 12:00am
  workflow_dispatch:



jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create and Load Environment Variables
        run: |
          cp .env.example .env
          export $(grep -v '^#' .env | xargs) 
          cat .env | sed 's/^/echo "/; s/$/" >> $GITHUB_ENV/' | bash

      - name: Run tests
        run: |
          source env/bin/activate
          pip install pytest
          pytest src/tests/

      - name: Export environment variables
        run: |
          export $(grep -v '^#' .env | xargs)

      - name: Log in to Docker Hub
        if: success()
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .

      - name: Push Docker Image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Send Failure Notification (If Tests Fail)
        if: failure()
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data '{
              "personalizations": [{"to": [{"email": "kdai3@dons.usfca.edu"}]}],
              "from": {"email": "kdai3@dons.usfca.edu"},
              "subject": "❌ Nightly Build Failed!",
              "content": [{"type": "text/plain", "value": "The nightly build has failed. Please check the logs in GitHub Actions."}]
            }'