name: Nightly Build and Push to Docker Hub

on:
  schedule:
    - cron: "15 5 * * *"  # SFtime 9:15 pM (PST, UTC-8)
  workflow_dispatch:  

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/  # Adjust based on your project structure

      - name: Log in to Docker Hub
        if: success()  # Only log in if tests pass
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .

      - name: Push Docker Image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Send Failure Notification (If Tests Fail)
        if: failure()
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data '{
              "personalizations": [{"to": [{"email": "kdai3@dons.usfca.edu"}]}],
              "from": {"email": "kdai3@dons.usfca.edu"},
              "subject": "❌ Nightly Build Failed!",
              "content": [{"type": "text/plain", "value": "The nightly build has failed. Please check the logs in GitHub Actions."}]
            }'