name: Nightly Build and Push to Docker Hub

on:
  schedule:

    - cron: "*/10 * * * *"  # run every 10 minutes
  workflow_dispatch:



jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=sqlite+aiosqlite:///test.db" >> $GITHUB_ENV
          echo "JWT_SECRET=mysecret" >> $GITHUB_ENV
          echo "JWT_ALGORITHM=HS256" >> $GITHUB_ENV
          echo "MAIL_USERNAME=test@example.com" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=yourpassword" >> $GITHUB_ENV
          echo "MAIL_FROM=noreply@example.com" >> $GITHUB_ENV
          echo "MAIL_PORT=587" >> $GITHUB_ENV
          echo "MAIL_SERVER=smtp.example.com" >> $GITHUB_ENV
          echo "MAIL_FROM_NAME=FastAPI App" >> $GITHUB_ENV
          echo "DOMAIN=localhost" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aiosqlite

      - name: Install Pytest
        run: pip install pytest

      - name: Run tests
        run: |
          ls -l src/tests/    
          pytest src/tests/ 

      - name: Log in to Docker Hub
        if: success()  # Only log in if tests pass
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .

      - name: Push Docker Image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Send Failure Notification (If Tests Fail)
        if: failure()
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data '{
              "personalizations": [{"to": [{"email": "kdai3@dons.usfca.edu"}]}],
              "from": {"email": "kdai3@dons.usfca.edu"},
              "subject": "❌ Nightly Build Failed!",
              "content": [{"type": "text/plain", "value": "The nightly build has failed. Please check the logs in GitHub Actions."}]
            }'